force-app/main/default/objects/Account_Field_Score__c/Account_Field_Score__c.object-meta.xml
<CustomObject>
    <description>Juntion object between Account and Fields Scores. When an account field value is set or change an Account Field Score record will be created.</description>
    <label>Account Field Score</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Field Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Field Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Field_Score__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The related Account for the Account Field Score, master of this record</description>
    <inlineHelpText>Please pick the account for this Account Field Score record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Field Scores</relationshipLabel>
    <relationshipName>Account_Field_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <formula>Field_Score__r.FieldName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Field_Score__c.field-meta.xml
<CustomField>
    <fullName>Field_Score__c</fullName>
    <description>The Field Score and Account are both master of the Account Field Score juntion object</description>
    <inlineHelpText>Please select the Score for the corresponding field value</inlineHelpText>
    <label>Field Score</label>
    <referenceTo>Field_Score__c</referenceTo>
    <relationshipLabel>Account Field Scores</relationshipLabel>
    <relationshipName>Account_Field_Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Field_Score__r.Score__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>This set the weight for the Account Field Score, determine by the primary asset class on the account level. Only credit and Public equity are applicable for now</description>
    <formula>CASE( TEXT(Account__r.Primary_Asset_Class__c), 
&quot;Credit&quot;,  Field_Score__r.Field_Weight__r.Credit_Weight__c , 
&quot;Equity&quot;, Field_Score__r.Field_Weight__r.Public_Equity_Weight__c ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weight_Score_Static__c.field-meta.xml
<CustomField>
    <fullName>Weight_Score_Static__c</fullName>
    <description>The Static version of the Weighted Score, used in the roll-up on the Account level</description>
    <label>Weight Score Static</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weighted_Score__c.field-meta.xml
<CustomField>
    <fullName>Weighted_Score__c</fullName>
    <formula>Score__c * Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weighted Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/Field_Score__c.object-meta.xml
<CustomObject>
    <description>Field Score records for the Account Ranking automation.</description>
    <label>Field Score</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Field Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Score__c/fields/Field_Weight__c.field-meta.xml
<CustomField>
    <fullName>Field_Weight__c</fullName>
    <description>The master for the Field Score, if there is no related weight the model will be incomplete</description>
    <label>Field Weight</label>
    <referenceTo>Field_Weight__c</referenceTo>
    <relationshipLabel>Field Scores</relationshipLabel>
    <relationshipName>Field_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <description>Field for the desired field score, should match the field weight</description>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/Hedge_Fund__c.field-meta.xml
<CustomField>
    <fullName>Hedge_Fund__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this field is checked then the score will only apply to account whose firm type is a Hedge Fund</description>
    <inlineHelpText>Please determine if the Score will only be for Hedge Funds</inlineHelpText>
    <label>Hedge Fund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The score for the field score record</description>
    <inlineHelpText>Please set the score for the field score, defaults to 0</inlineHelpText>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value for a particular Field Score this is used to in the Account Ranking Close to search agisnt Field Score records</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Weight__c/Field_Weight__c.object-meta.xml
<CustomObject>
    <description>Controls the weights for the Field Score. There should be a field and corresponding vertical weight per record</description>
    <label>Field Weight</label>
    <nameField>
        <label>Field Weight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Weight__c/fields/Credit_Weight__c.field-meta.xml
<CustomField>
    <fullName>Credit_Weight__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The field weight for the Credit asset class. Determine how much weight is applied to a field when the asset class is Credit</description>
    <label>Credit Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Field_Weight__c/fields/Public_Equity_Weight__c.field-meta.xml
<CustomField>
    <fullName>Public_Equity_Weight__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The weight for a Public Equity asset class, controls how much weight is applied to the child field scores when the asset class is Public Equity Weight</description>
    <label>Public Equity Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/FieldScoreFieldWeightModel.cls
/**
 * @description       : 
 * @author            : Kyle (RadixBay)
 * @group             : 
 * @last modified on  : 05-15-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class FieldScoreFieldWeightModel implements Queueable{

    public String executionType = '';
    List<ID> fieldsToUpdate;

    
    public FieldScoreFieldWeightModel(String executionType, List<ID> fieldsToUpdate){
        this.executionType = executionType;
        this.fieldsToUpdate = fieldsToUpdate;
    }

    //Queueable class that executes the account updates through batches 
    public void execute(System.QueueableContext ctx){
        if (executionType.equals('score')){
            fieldScoreUpdatesQueue(fieldsToUpdate);
        }
    }
    
    //Field Score Change Setup
    public static void setupFieldScoreChanges(Map<Id, SObject> oldFieldScoreValues, Map<Id, SObject> newFieldScoreValues){
        
        Map<Id, Field_Score__c> fieldScoreBeforeUpdate = new Map<Id, Field_Score__c>();
        Map<Id, Field_Score__c> fieldScoreAfterUpdate = new Map<Id, Field_Score__c>();
        Map<Id, Field_Score__c> newMap = (Map<Id, Field_Score__c>)newFieldScoreValues;
        Map<Id, Field_Score__c> oldMap = (Map<Id, Field_Score__c>)oldFieldScoreValues;

        // Iterate over the incoming Maps and copy them to Maps we will use in the Model.
        for(Field_Score__c fs : newMap.values()){
            if (oldFieldScoreValues != null){
                fieldScoreBeforeUpdate.put(fs.Id, oldMap.get(fs.Id));
            }
                fieldScoreAfterUpdate.put(fs.Id, fs); 
        }

        List<Id> fieldScoreIDsToUpdate = new List<Id> (fieldScoreAfterUpdate.keySet());
        Map<Integer, Id> fieldScoreMapForLoop = new Map<Integer, Id>();

        for(Integer fsi = 0; fsi < fieldScoreAfterUpdate.size(); fsi++){
            fieldScoreMapForLoop.put(fsi, fieldScoreIDsToUpdate.get(fsi));
        }

        List<ID> fieldScoresChanged = new List<ID>();
        
        // This loop parses through both incoming Account Maps and determines the fields that were updated.
        // We only check the relative Field Score values set on the account. 
        for(Integer i = 0; i < fieldScoreAfterUpdate.size(); i++){                    
            // Possible rewrite for this needed to support the Map Datatypes coming in.
            ID accountMapId = fieldScoreMapForLoop.get(i);
            Field_Score__c oldFieldScoreValue = fieldScoreBeforeUpdate.get(accountMapId);
            Field_Score__c newFieldScoreValue = fieldScoreAfterUpdate.get(accountMapId);

            if (oldFieldScoreValue.Score__c != newFieldScoreValue.Score__c){
                fieldScoresChanged.add(newFieldScoreValue.Id);
            }
        }

        if (!fieldScoresChanged.isEmpty()){
            initialFieldScoreUpdates(fieldScoresChanged);
        }

    }
    //Field Weight Change Setup
    public static void setupFieldWeightChanges(Map<Id, SObject> oldFieldWeightValues, Map<Id, SObject> newFieldWeightValues){
        
        Map<Id, Field_Weight__c> fieldWeightBeforeUpdate = new  Map<Id, Field_Weight__c>();
        Map<Id, Field_Weight__c> fieldWeightAfterUpdate = new  Map<Id, Field_Weight__c>();
        Map<Id, Field_Weight__c> newMap = (Map<Id, Field_Weight__c>)newFieldWeightValues;
        Map<Id, Field_Weight__c> oldMap = (Map<Id, Field_Weight__c>)oldFieldWeightValues;

        // Iterate over the incoming Maps and copy them to Maps we will use in the Model.
        for(Field_Weight__c fw : newMap.values()){
            if (oldFieldWeightValues != null){
                fieldWeightBeforeUpdate.put(fw.Id, oldMap.get(fw.Id));
            }
                fieldWeightAfterUpdate.put(fw.Id, fw); 
        }

        List<Id> fieldWeightIDsToUpdate = new List<Id> (fieldWeightAfterUpdate.keySet());

        List<ID> fieldWeightsChanged = new List<ID>();
        
        // This loop parses through both incoming Account Maps and determines the fields that were updated.
        // We only check the relative Field Score values set on the account. 
        for(Integer i = 0; i < fieldWeightAfterUpdate.size(); i++){                    
            // Possible rewrite for this needed to support the Map Datatypes coming in.
            ID accountMapId = fieldWeightIDsToUpdate.get(i);
            Field_Weight__c oldFieldWeightValue = fieldWeightBeforeUpdate.get(accountMapId);
            Field_Weight__c newFieldWeightValue = fieldWeightAfterUpdate.get(accountMapId);

            
            if ((oldFieldWeightValue.Credit_Weight__c != newFieldWeightValue.Credit_Weight__c) || oldFieldWeightValue.Public_Equity_Weight__c != newFieldWeightValue.Public_Equity_Weight__c){
                fieldWeightsChanged.add(newFieldWeightValue.Id);
            }
        }

        if (!fieldWeightsChanged.isEmpty()){
            List<Field_Score__c> fieldScoresToUpdate = [SELECT Id from Field_Score__c WHERE Field_Weight__c IN :fieldWeightsChanged];
            List<ID> fieldScoreRecordIDs = new List<ID>();
            for (Field_Score__c fieldScore : fieldScoresToUpdate){
                fieldScoreRecordIDs.add(fieldScore.Id);
            }
            initialFieldScoreUpdates(fieldScoreRecordIDs);
        }

    }

    /* 
     * This method only runs once at the start of every change. If this is not done, the first request is ran synchronously.
     * This would cause potential issues with Apex CPU Timeout limits. This runs the first call asynchronously so that we have 60 seconds
     * to perform a round of AFS record updates. Every round in the Queueable context after this will be asynchronous as well.
     */  
    @future
    private static void initialFieldScoreUpdates(List<Id> fieldScoreIDsToUpdate){

        List<Id> fieldScoreIDsRemaining = fieldScoreUpdates(fieldScoreIDsToUpdate);

        if(!fieldScoreIDsRemaining.isEmpty()){
            fieldScoreUpdatesQueue(fieldScoreIDsRemaining);
        }

    }

    private static void fieldScoreUpdatesQueue(List<Id> fieldScoreIDsToUpdate){

        List<Id> fieldScoreIDsRemaining = fieldScoreUpdates(fieldScoreIDsToUpdate);

        if(!fieldScoreIDsRemaining.isEmpty()){
            String type = 'score';
            List<ID> queueID = new List<ID>();
            queueID.add(System.enqueueJob(new FieldScoreFieldWeightModel(type, fieldScoreIDsRemaining)));
        }

    }

    // The main logic used to update Field Scores.
    private static List<Id> fieldScoreUpdates(List<Id> fieldScoreIDsToUpdate){

        List<ID> fieldScoreIDBatch = new List<ID>();

        // If we hit 50 field score records, stop adding records and queue the rest for another run.
        Integer i = 0;
        for (ID fieldScoreID : fieldScoreIDsToUpdate){
            if(i != 2){
                fieldScoreIDBatch.add(fieldScoreID);
                i++;
            }
        }
        System.debug('Initial list size: ' + fieldScoreIDsToUpdate.size());
        System.debug('ID list size: ' + fieldScoreIDBatch.size());

        List<Account_Field_Score__c> accountFieldScoresToUpdate = [SELECT Id, Field__c, Account__c, Weighted_Score__c, Weight__c, Weight_Score_Static__c FROM Account_Field_Score__c WHERE Field_Score__c IN :fieldScoreIDBatch];

        // This static field is derived from the Weighted_Score__c formula field. This is used in the Account Priority rank calculation on the account.
        // The Weighted score on the account record is a rollup field from the Weight_Score_Static__c field.
        for(Account_Field_Score__c accountFieldScore : accountFieldScoresToUpdate){
            // If the Field in question is Investment Instruments, then we must make the sum calculation for the field score numbers, instead of direct update.
            if (accountFieldScore.Field__c == 'Investment Instruments'){
                Double investmentInstrumentSum = 0;
                Boolean accountHF = false;
                Account accountToUpdate = [SELECT Id, Investment_Instruments__c, Client_Type__c FROM Account WHERE Id =:accountFieldScore.Account__c LIMIT 1];

                if (accountToUpdate.Client_Type__c == 'Hedge Fund'){
                    accountHF = true;
                }

                List<String> investmentInstrumentFieldScores = accountToUpdate.Investment_Instruments__c.split(';');

                List<Field_Score__c> highestFieldScore = [SELECT Id, FieldName__c, Value__c, Score__c FROM Field_Score__c WHERE FieldName__c = :accountFieldScore.Field__c AND Value__c IN :investmentInstrumentFieldScores AND Hedge_Fund__c =:accountHF ORDER BY Score__c DESC];

                for( Field_Score__c score : highestFieldScore){
                    investmentInstrumentSum += score.Score__c;
                }

                Double weightValue = accountFieldScore.Weight__c * 0.01;
                accountFieldScore.Weight_Score_Static__c = investmentInstrumentSum * weightValue;

            } else {
                accountFieldScore.Weight_Score_Static__c = accountFieldScore.Weighted_Score__c;
            }
        }

        update accountFieldScoresToUpdate;

        /*
        * This loop will remove the field score records that were just updated to setup the next batch for queue.
        * We are not able to remove the Field Score records in the first for each loop, as it throws a System.FinalException
        * Hence the need for this below for each loop.
        */
        Integer fieldScoreIDsToUpdatePosition = 0;
        System.debug('Initial list size: ' + fieldScoreIDsToUpdate.size());
        System.debug('ID list size: ' + fieldScoreIDBatch.size());
        for (ID fsid : fieldScoreIDBatch){
            if(fieldScoreIDsToUpdatePosition != 2 && fieldScoreIDsToUpdatePosition < fieldScoreIDsToUpdate.size()){
                fieldScoreIDsToUpdate.remove(fieldScoreIDsToUpdatePosition);
                fieldScoreIDsToUpdatePosition++; 
                System.debug('Remove Size' + fieldScoreIDsToUpdate.size());
            }
        }

        return fieldScoreIDsToUpdate;
    }
}