force-app/main/default/objects/Account_Field_Score__c/Account_Field_Score__c.object-meta.xml
<CustomObject>
    <description>Juntion object between Account and Fields Scores. When an account field value is set or change an Account Field Score record will be created.</description>
    <label>Account Field Score</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Field Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Field Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Field_Score__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The related Account for the Account Field Score, master of this record</description>
    <inlineHelpText>Please pick the account for this Account Field Score record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Field Scores</relationshipLabel>
    <relationshipName>Account_Field_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Field_Score__c.field-meta.xml
<CustomField>
    <fullName>Field_Score__c</fullName>
    <description>The Field Score and Account are both master of the Account Field Score juntion object</description>
    <inlineHelpText>Please select the Score for the corresponding field value</inlineHelpText>
    <label>Field Score</label>
    <referenceTo>Field_Score__c</referenceTo>
    <relationshipLabel>Account Field Scores</relationshipLabel>
    <relationshipName>Account_Field_Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>The field value from the Account, set by the automation that creates/updates the Account Field Score record</description>
    <inlineHelpText>Please set this field to the value of the field on the Account</inlineHelpText>
    <label>Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Field_Score__r.Score__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>This set the weight for the Account Field Score, determine by the primary asset class on the account level. Only credit and Public equity are applicable for now</description>
    <formula>CASE( TEXT(Account__r.Primary_Asset_Class__c), 
&quot;Credit&quot;,  Field_Score__r.Field_Weight__r.Credit_Weight__c , 
&quot;Equity&quot;, Field_Score__r.Field_Weight__r.Public_Equity_Weight__c ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weight_Score_Static__c.field-meta.xml
<CustomField>
    <fullName>Weight_Score_Static__c</fullName>
    <description>The Static version of the Weighted Score, used in the roll-up on the Account level</description>
    <label>Weight Score Static</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weighted_Score__c.field-meta.xml
<CustomField>
    <fullName>Weighted_Score__c</fullName>
    <formula>Score__c * Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weighted Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/Field_Score__c.object-meta.xml
<CustomObject>
    <description>Field Score records for the Account Ranking automation.</description>
    <label>Field Score</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Field Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Score__c/fields/Field_Weight__c.field-meta.xml
<CustomField>
    <fullName>Field_Weight__c</fullName>
    <description>The master for the Field Score, if there is no related weight the model will be incomplete</description>
    <label>Field Weight</label>
    <referenceTo>Field_Weight__c</referenceTo>
    <relationshipLabel>Field Scores</relationshipLabel>
    <relationshipName>Field_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <description>Field for the desired field score, should match the field weight</description>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The score for the field score record</description>
    <inlineHelpText>Please set the score for the field score, defaults to 0</inlineHelpText>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value for a particular Field Score this is used to in the Account Ranking Close to search agisnt Field Score records</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Weight__c/Field_Weight__c.object-meta.xml
<CustomObject>
    <description>Controls the weights for the Field Score. There should be a field and corresponding vertical weight per record</description>
    <label>Field Weight</label>
    <nameField>
        <label>Field Weight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Weight__c/fields/Credit_Weight__c.field-meta.xml
<CustomField>
    <fullName>Credit_Weight__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The field weight for the Credit asset class. Determine how much weight is applied to a field when the asset class is Credit</description>
    <label>Credit Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Field_Weight__c/fields/Public_Equity_Weight__c.field-meta.xml
<CustomField>
    <fullName>Public_Equity_Weight__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The weight for a Public Equity asset class, controls how much weight is applied to the child field scores when the asset class is Public Equity Weight</description>
    <label>Public Equity Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/FieldWeightTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-10-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@IsTest
private class FieldWeightTriggerHandlerTest {
    // Setup Test Data (only used during test, not commited to database)
    @TestSetup
    static void setupData(){
        Account testAccount = new Account(
            RecordTypeId = '0120X000000gKhsQAE', 
            Name = 'RadixBay1', 
            Country__c = 'United States',
            Territory__c = 'North America',
            Primary_Asset_Class__c = 'Equity',
            Pod_Account__c = false,
            Forum_Tier__c = '2'
        );
        insert testAccount;

        Field_Weight__c testweight = new Field_Weight__c (
            Credit_Weight__c = 10,
            Public_Equity_Weight__c = 5,
            Name = 'Style'
        );
        insert testweight;

        Field_Score__c GrowthScore = new Field_Score__c (
            FieldName__c = 'Style',
            Value__c = 'Growth', 
            Score__c = 6,
            Field_Weight__c = testweight.id
        );
        insert GrowthScore;

        Account_Field_Score__c Styleconnection = new Account_Field_Score__c(
            Account__c = testAccount.id,
            Field_Score__c = GrowthScore.Id,
            Weight_Score_Static__c = 0.3,
            Field_Value__c = 'Growth'
        );
        insert Styleconnection;

    }

    /* Test to confirm a Field Weight can be inserted */
    @isTest
    private static void FieldWeightInsert(){
        Field_Weight__c testfieldweight = new Field_Weight__c(
            Name = 'Test 2', 
            Public_Equity_Weight__c = 25, 
            Credit_Weight__c = 25
        );
        insert testfieldweight;

        List<Field_Weight__c> weightcreated = [SELECT Id, Public_Equity_Weight__c FROM Field_Weight__c WHERE Name = 'Test 2' ];

        System.debug('# of Weight created: ' + weightcreated.size());
        System.assertEquals(weightcreated.size(), 1, 'Actual number of Weights created: ' + weightcreated.size());
    }
    /* Test to confirm a Field Weight can be updated */
    @isTest
    private static void FieldWeightUpdate(){
        Field_Weight__c testfieldweight = [SELECT Id, Public_Equity_Weight__c FROM Field_Weight__c LIMIT 1];
        testfieldweight.Public_Equity_Weight__c = 30;
        update testfieldweight;

        System.debug('Updated Weight: ' + testfieldweight.Public_Equity_Weight__c);
        System.assertEquals(testfieldweight.Public_Equity_Weight__c, 30, 'Actual weight set: ' + testfieldweight.Public_Equity_Weight__c);
    }

    /*
    * Test class for Account Ranking Model Field Weight 
    * When the Public Equity Weight field is updated on a Field Weight record, all related AFS records will be updated with the new Public Equity Weight.
    * Also the Weight Score Static field on related AFS should match the Weight Score field 
    */
    @isTest
    private static void AccountRankingWeightupdated(){
        Field_Weight__c testfieldweight = [SELECT Id, Public_Equity_Weight__c FROM Field_Weight__c LIMIT 1];
        Account_Field_Score__c relatedtestAFS = [SELECT Id, Weight_Score_Static__c,Weight__c,Weighted_Score__c FROM Account_Field_Score__c LIMIT 1];

        Double oldWeight = relatedtestAFS.Weight__c;
        Double oldweightscore = relatedtestAFS.Weighted_Score__c;
        System.debug('AFS:' + oldWeight + '   FS:'+testfieldweight.Public_Equity_Weight__c);
        System.assertEquals(testfieldweight.Public_Equity_Weight__c, oldWeight, 'AFS Weight doesnt match weight FROM field weight record');

        //Update weight field
        Test.startTest();{
            
        
        testfieldweight.Public_Equity_Weight__c = 35;
        update testfieldweight; 
            
        }
        Test.stopTest();

        relatedtestAFS = [SELECT Id, Weight_Score_Static__c, Weight__c, Weighted_Score__c FROM Account_Field_Score__c LIMIT 1];
        Double newWeight = relatedtestAFS.Weight__c;
        Double newweightScore = relatedtestAFS.Weighted_Score__c;
        Double weightscorestatic = relatedtestAFS.Weight_Score_Static__c;

        System.debug('AFS:' + newWeight + '   FS:' + testfieldweight.Public_Equity_Weight__c);
        System.assertEquals(testfieldweight.Public_Equity_Weight__c, newWeight, 'Weight wasnt updated with new weight');
        System.assertNotEquals(newWeight, oldWeight, 'New & Old Weight Matches on AFS');
        System.debug('New Weight Score: ' + newWeightScore + '   New Weight Static: ' + weightscorestatic);
        System.assertEquals(newWeightScore, weightscorestatic, 'Static Weight wasnt updated with new weight');
    }

}