force-app/main/default/objects/Account_Field_Score__c/Account_Field_Score__c.object-meta.xml
<CustomObject>
    <description>Juntion object between Account and Fields Scores. When an account field value is set or change an Account Field Score record will be created.</description>
    <label>Account Field Score</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Field Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Field Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Field_Score__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The related Account for the Account Field Score, master of this record</description>
    <inlineHelpText>Please pick the account for this Account Field Score record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Field Scores</relationshipLabel>
    <relationshipName>Account_Field_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Field_Score__c.field-meta.xml
<CustomField>
    <fullName>Field_Score__c</fullName>
    <description>The Field Score and Account are both master of the Account Field Score juntion object</description>
    <inlineHelpText>Please select the Score for the corresponding field value</inlineHelpText>
    <label>Field Score</label>
    <referenceTo>Field_Score__c</referenceTo>
    <relationshipLabel>Account Field Scores</relationshipLabel>
    <relationshipName>Account_Field_Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>The field value from the Account, set by the automation that creates/updates the Account Field Score record</description>
    <inlineHelpText>Please set this field to the value of the field on the Account</inlineHelpText>
    <label>Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Field_Score__r.Score__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>This set the weight for the Account Field Score, determine by the primary asset class on the account level. Only credit and Public equity are applicable for now</description>
    <formula>CASE( TEXT(Account__r.Primary_Asset_Class__c), 
&quot;Credit&quot;,  Field_Score__r.Field_Weight__r.Credit_Weight__c , 
&quot;Equity&quot;, Field_Score__r.Field_Weight__r.Public_Equity_Weight__c ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weight_Score_Static__c.field-meta.xml
<CustomField>
    <fullName>Weight_Score_Static__c</fullName>
    <description>The Static version of the Weighted Score, used in the roll-up on the Account level</description>
    <label>Weight Score Static</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Field_Score__c/fields/Weighted_Score__c.field-meta.xml
<CustomField>
    <fullName>Weighted_Score__c</fullName>
    <formula>Score__c * Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weighted Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/Field_Score__c.object-meta.xml
<CustomObject>
    <description>Field Score records for the Account Ranking automation.</description>
    <label>Field Score</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Field Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Score__c/fields/Field_Weight__c.field-meta.xml
<CustomField>
    <fullName>Field_Weight__c</fullName>
    <description>The master for the Field Score, if there is no related weight the model will be incomplete</description>
    <label>Field Weight</label>
    <referenceTo>Field_Weight__c</referenceTo>
    <relationshipLabel>Field Scores</relationshipLabel>
    <relationshipName>Field_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <description>Field for the desired field score, should match the field weight</description>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The score for the field score record</description>
    <inlineHelpText>Please set the score for the field score, defaults to 0</inlineHelpText>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Score__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value for a particular Field Score this is used to in the Account Ranking Close to search agisnt Field Score records</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Weight__c/Field_Weight__c.object-meta.xml
<CustomObject>
    <description>Controls the weights for the Field Score. There should be a field and corresponding vertical weight per record</description>
    <label>Field Weight</label>
    <nameField>
        <label>Field Weight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Weights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Weight__c/fields/Credit_Weight__c.field-meta.xml
<CustomField>
    <fullName>Credit_Weight__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The field weight for the Credit asset class. Determine how much weight is applied to a field when the asset class is Credit</description>
    <label>Credit Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Field_Weight__c/fields/Public_Equity_Weight__c.field-meta.xml
<CustomField>
    <fullName>Public_Equity_Weight__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The weight for a Public Equity asset class, controls how much weight is applied to the child field scores when the asset class is Public Equity Weight</description>
    <label>Public Equity Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : LeeWayne (RadixBay)
 * @group             : 
 * @last modified on  : 05-17-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@IsTest
public class AccountTriggerHandlerTest {
    
    /*Test Setup */
    @TestSetup
    static void setupData(){

        Id prospectId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();

        Account testAccount = new Account(
            RecordTypeId = prospectId,
            Name = 'RadixBay1',
            Country__c = 'United States',
            Territory__c = 'North America',
            Primary_Asset_Class__c = 'Credit',
            Pod_Account__c = false,
            Forum_Tier__c = '2'
        );
        insert testAccount;

        Field_Weight__c testweight = new Field_Weight__c (
            Credit_Weight__c = 10,
            Public_Equity_Weight__c = 5,
            Name = 'Style'
        );
        insert testweight;

        Field_Score__c GrowthScore = new Field_Score__c (
            FieldName__c = 'Style',
            Value__c= 'Growth',
            Score__c = 6,
            Field_Weight__c = testweight.id
        );
        Field_Score__c ValueScore = new Field_Score__c (
            FieldName__c = 'Style',
            Value__c = 'Value',
            Score__c = 10,
            Field_Weight__c = testweight.id
        );
        
        insert GrowthScore;
        insert ValueScore;
    
    }
    /*Test to confirm an Account can be inserted */
    @isTest
    private static void accountInsert(){
        // Create an Account, then insert the Account in order to execute the Before Insert & After Insert triggers.
        Account testAccount = new Account(
            RecordTypeId = '0120X000000gKhsQAE', 
            Name = 'RadixBay2', 
            Primary_Asset_Class__c = 'Credit',
            Country__c = 'United States',
            Territory__c = 'North America',
            Pod_Account__c = false,
            Forum_Tier__c = '2'
        );
        insert testAccount;
    }

    /*Test to confirm an Account can be updated */
    @isTest
    private static void accountUpdate(){
        // Pull an Account, update a field then update the Account to trigger the Before Update & After update triggers
        Account testaccount = [select Id, Name, Country__c from Account LIMIT 1];
        testaccount.Country__c = 'Aland Islands';
        update testaccount;
    }

    /*
    Account Ranking Model Account Field Score 
    When a field is set to a value, the AccountRankingModel is called.
    This checks for a Account Field Score record, if none exists for that field, it creates it.
    If the field is updated to a different value, then the linked Field Score is updated to the correct field score record.
    */
    @isTest
    private static void checkAccountScore(){
        
        /*Pull an Account and set the Style field */
        Test.startTest();        
            Account testaccount = [select Id, Style__c from Account LIMIT 1];
            testaccount.Style__c = 'Growth';
            update testaccount;
            System.debug('TESTING TESTING UPDATE');
        Test.stopTest();
        
        /*An Account Field Score record should have been created because the field was set */
        Account_Field_Score__c Styleconnection = [select Id, Account__c, Field_Score__c, Field_Value__c, Score__c, Weight__c, Weighted_Score__c, Weight_Score_Static__c from Account_Field_Score__c LIMIT 1];

        List<Field_Score__c> StyleScore = [select Id, Score__c from Field_Score__c where FieldName__c = 'Style' AND Value__c = 'Growth' ORDER BY Name ASC];
        Field_Score__c growthScore = StyleScore[0];

        Double createdWeight = Styleconnection.Weight_Score_Static__c;
        /*Test to see if the related Account Field Score was create with the create Field Score record */
        System.debug('AFS:' + Styleconnection.Field_Score__c + '   FS:' + growthScore.Id);
        Assert.areEqual(Styleconnection.Field_Score__c, growthScore.Id);
        Assert.areEqual(Styleconnection.Field_Value__c, testaccount.Style__c);
        Assert.areEqual(Styleconnection.Weight_Score_Static__c, Styleconnection.Weighted_Score__c);

    }
}